# Generated by Django 4.2.6 on 2024-07-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
            },
        ),
        migrations.AlterModelOptions(
            name="firefighter",
            options={"verbose_name": "Bombeiro", "verbose_name_plural": "Bombeiros"},
        ),
    ]
