# Generated by Django 4.2.6 on 2024-07-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="suspect_problems",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="reports",
                to="reports.suspectproblems",
            ),
        ),
    ]
