# Generated by Django 4.2.6 on 2024-06-10 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProblems",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Problema", max_length=100, verbose_name="Problema"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubSubProceeding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Procedimento",
                        max_length=100,
                        verbose_name="Procedimento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubSubSignsAndSymptoms",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sinais e sintomas",
                        max_length=100,
                        verbose_name="Sinais e sintomas",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="proceeding",
            name="sub_sub_proceed",
        ),
        migrations.RemoveField(
            model_name="signsandsymptoms",
            name="sub_sub_symptoms",
        ),
        migrations.AlterField(
            model_name="report",
            name="disposable_materials",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.disposablematerials"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="hospital_materials",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.hospitalmaterials"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="proceeding",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.proceeding"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.signsandsymptoms"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="suspect_problems",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.suspectproblems"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="type_of_occurrences",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.typeofoccurrence"
            ),
        ),
        migrations.CreateModel(
            name="SubSignsAndSymptoms",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sinais e sintomas",
                        max_length=100,
                        verbose_name="Sinais e sintomas",
                    ),
                ),
                (
                    "sub_sub_symptoms",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="child_sub_symptoms",
                        to="reports.subsubsignsandsymptoms",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubProceeding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Procedimento",
                        max_length=100,
                        verbose_name="Procedimento",
                    ),
                ),
                (
                    "sub_sub_proceed",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="child_sub_proceedings",
                        to="reports.subsubproceeding",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="proceeding",
            name="sub_proceed",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="child_proceedings",
                to="reports.subproceeding",
            ),
        ),
        migrations.AlterField(
            model_name="signsandsymptoms",
            name="sub_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_child_sub_symptoms",
                to="reports.subsignsandsymptoms",
            ),
        ),
        migrations.AlterField(
            model_name="suspectproblems",
            name="sub_problems",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="child_problems",
                to="reports.subproblems",
            ),
        ),
    ]
