# Generated by Django 4.2.6 on 2024-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0002_subproblems_subsubproceeding_subsubsignsandsymptoms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceeding",
            name="sub_proceed",
            field=models.ManyToManyField(
                related_name="child_proceedings", to="reports.subproceeding"
            ),
        ),
        migrations.AlterField(
            model_name="signsandsymptoms",
            name="sub_symptoms",
            field=models.ManyToManyField(
                related_name="child_child_sub_symptoms",
                to="reports.subsignsandsymptoms",
            ),
        ),
        migrations.AlterField(
            model_name="subproceeding",
            name="sub_sub_proceed",
            field=models.ManyToManyField(
                related_name="child_sub_proceedings", to="reports.subsubproceeding"
            ),
        ),
        migrations.AlterField(
            model_name="subsignsandsymptoms",
            name="sub_sub_symptoms",
            field=models.ManyToManyField(
                related_name="child_sub_symptoms", to="reports.subsubsignsandsymptoms"
            ),
        ),
        migrations.AlterField(
            model_name="suspectproblems",
            name="sub_problems",
            field=models.ManyToManyField(
                related_name="child_problems", to="reports.subproblems"
            ),
        ),
    ]
