# Generated by Django 4.2.6 on 2024-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_report_suspect_problems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspectproblems",
            name="sub_suspect_problems",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="suspect_problems",
                to="reports.subsuspectproblems",
            ),
        ),
    ]
