# Generated by Django 4.2.6 on 2024-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_proceeding_sub_proceed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspectproblems",
            name="sub_problems",
            field=models.ManyToManyField(
                blank=True, related_name="child_problems", to="reports.subproblems"
            ),
        ),
    ]
