# Generated by Django 4.2.6 on 2024-07-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_suspectproblems_sub_suspect_problems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proceeding",
            name="sub_proceed",
        ),
        migrations.RemoveField(
            model_name="report",
            name="proceeding",
        ),
        migrations.RemoveField(
            model_name="report",
            name="signs_and_symptoms",
        ),
        migrations.RemoveField(
            model_name="report",
            name="suspect_problems",
        ),
        migrations.RemoveField(
            model_name="signsandsymptoms",
            name="sub_symptoms",
        ),
        migrations.RemoveField(
            model_name="subproceeding",
            name="sub_sub_proceed",
        ),
        migrations.RemoveField(
            model_name="subsignsandsymptoms",
            name="sub_sub_symptoms",
        ),
        migrations.RemoveField(
            model_name="suspectproblems",
            name="sub_suspect_problems",
        ),
        migrations.AlterField(
            model_name="signsandsymptoms",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.report"
            ),
        ),
    ]
