# Generated by Django 4.2.6 on 2024-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_suspectproblems_sub_problems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signsandsymptoms",
            name="sub_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_child_sub_symptoms",
                to="reports.subsignsandsymptoms",
            ),
        ),
        migrations.AlterField(
            model_name="subsignsandsymptoms",
            name="sub_sub_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_sub_symptoms",
                to="reports.subsubsignsandsymptoms",
            ),
        ),
    ]
