# Generated by Django 4.2.6 on 2024-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_remove_proceeding_sub_proceed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proceeding",
            name="report",
        ),
        migrations.RemoveField(
            model_name="signsandsymptoms",
            name="report",
        ),
        migrations.RemoveField(
            model_name="suspectproblems",
            name="report",
        ),
        migrations.AddField(
            model_name="report",
            name="proceeding",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.proceeding"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.signsandsymptoms"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="suspect_problems",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="reports",
                to="reports.suspectproblems",
            ),
        ),
    ]
