# Generated by Django 4.2.6 on 2024-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_remove_proceeding_report_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="type_of_occurrences",
            new_name="type_of_occurrence",
        ),
        migrations.AlterField(
            model_name="report",
            name="suspect_problems",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.suspectproblems"
            ),
        ),
    ]
