# Generated by Django 4.2.6 on 2024-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_signsandsymptoms_sub_symptoms_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="decision_transport",
        ),
        migrations.RemoveField(
            model_name="report",
            name="driving_style",
        ),
        migrations.RemoveField(
            model_name="report",
            name="victim_was",
        ),
        migrations.AlterField(
            model_name="subproceeding",
            name="sub_sub_proceed",
            field=models.ManyToManyField(
                blank=True,
                related_name="child_sub_proceedings",
                to="reports.subsubproceeding",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="decision_transport",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="reports",
                to="reports.transportdecision",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="driving_style",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="reports", to="reports.drivingstyle"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="victim_was",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="reports", to="reports.victimwas"
            ),
        ),
    ]
