# Generated by Django 4.2.6 on 2024-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_remove_report_decision_transport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="decision_transport",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.transportdecision"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="driving_style",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.drivingstyle"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="victim_was",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.victimwas"
            ),
        ),
    ]
