# Generated by Django 4.2.6 on 2024-07-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0006_rename_type_of_occurrences_report_type_of_occurrence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablematerials",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8", "8"),
                    ("12", "12"),
                    ("20", "20"),
                    ("H", "H"),
                    ("P", "P"),
                    ("O", "O"),
                    ("G", "G"),
                    ("N", "N"),
                    ("PP", "PP"),
                    ("M", "M"),
                    ("ADULTO", "ADULTO"),
                    ("INFANTIL", "INFANTIL"),
                ],
                help_text="Tamanho",
                max_length=100,
                null=True,
                verbose_name="Tamanho",
            ),
        ),
        migrations.AlterField(
            model_name="hospitalmaterials",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8", "8"),
                    ("12", "12"),
                    ("20", "20"),
                    ("H", "H"),
                    ("P", "P"),
                    ("O", "O"),
                    ("G", "G"),
                    ("N", "N"),
                    ("PP", "PP"),
                    ("M", "M"),
                    ("ADULTO", "ADULTO"),
                    ("INFANTIL", "INFANTIL"),
                ],
                help_text="Tamanho",
                max_length=100,
                null=True,
                verbose_name="Tamanho",
            ),
        ),
    ]
