# Generated by Django 4.2.6 on 2024-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_alter_disposablematerials_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="sub_proceeding",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.subproceeding"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sub_signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.subsignsandsymptoms"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sub_sub_proceeding",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.subsubproceeding"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sub_sub_signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.subsubsignsandsymptoms"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sub_suspect_problems",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="reports.subsuspectproblems"
            ),
        ),
    ]
