# Generated by Django 4.2.6 on 2024-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_alter_report_decision_transport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")],
                help_text="Sexo",
                max_length=10,
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
