# Generated by Django 4.2.6 on 2024-07-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0008_report_sub_proceeding_report_sub_signs_and_symptoms_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="vitalsigns",
            old_name="perfusion_greater_than_two_seconds",
            new_name="perfusion_is_greater_than_two_seconds",
        ),
        migrations.RemoveField(
            model_name="vitalsigns",
            name="perfusion_less_than_two_seconds",
        ),
    ]
