# Generated by Django 4.2.6 on 2024-07-31 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "reports",
            "0009_rename_perfusion_greater_than_two_seconds_vitalsigns_perfusion_is_greater_than_two_seconds_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Data do relatório",
                null=True,
                verbose_name="Data do relatório",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
