# Generated by Django 4.2.6 on 2024-07-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("reports", "0010_alter_report_report_date_alter_report_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="anamnesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.anamnesis",
                verbose_name="Anamnese",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="cinematic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.cinematic",
                verbose_name="Avaliação de Cinemática",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="decision_transport",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.transportdecision",
                verbose_name="Decisão de transporte",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="disposable_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.disposablematerials",
                verbose_name="Materiais descartáveis",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="driving_style",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.drivingstyle",
                verbose_name="Forma de condução",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="general_registration",
            field=models.CharField(
                blank=True,
                help_text="RG/CPF do paciente",
                max_length=100,
                null=True,
                verbose_name="RG/CPF do paciente",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="gestacional_anamnesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.gestacionalanamnesis",
                verbose_name="Anamnese gestacional",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="hospital_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.hospitalmaterials",
                verbose_name="Materiais hospitalares",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_disposable_materials",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros materiais descartáveis",
                null=True,
                verbose_name="Outros materiais descartáveis",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_hospital_materials",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros materiais hospitalares",
                null=True,
                verbose_name="Outros materiais hospitalares",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_occurrence",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros tipos de ocorrências",
                null=True,
                verbose_name="Outro Tipo de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_problems",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros problemas",
                null=True,
                verbose_name="Outros problemas",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_proceeding",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros procedimentos",
                null=True,
                verbose_name="Outro procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_signs_and_symptoms",
            field=models.TextField(
                blank=True,
                help_text="Descrição para outros sinais e sintomas",
                null=True,
                verbose_name="Outros sinais e sintomas",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="proceeding",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.proceeding",
                verbose_name="Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="service_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.serviceteam",
                verbose_name="Time de serviço",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.signsandsymptoms",
                verbose_name="Sinais e sintomas",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sub_proceeding",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.subproceeding",
                verbose_name="Sub-Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sub_signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.subsignsandsymptoms",
                verbose_name="Sub-Sinais e sintomas",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sub_sub_proceeding",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.subsubproceeding",
                verbose_name="Sub-Sub-Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sub_sub_signs_and_symptoms",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.subsubsignsandsymptoms",
                verbose_name="Sub-Sub-Sinais e sintomas",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="sub_suspect_problems",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.subsuspectproblems",
                verbose_name="Sub-Problemas suspeitos",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="suspect_problems",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.suspectproblems",
                verbose_name="Problemas suspeitos",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="transport_informations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.transportinformations",
                verbose_name="Informações de transporte",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="type_of_occurrence",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.typeofoccurrence",
                verbose_name="Tipo de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="victim_was",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                to="reports.victimwas",
                verbose_name="Vítima era",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="vital_signs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reports.vitalsigns",
                verbose_name="Sinais vitais",
            ),
        ),
        migrations.AlterField(
            model_name="serviceteam",
            name="name_demandante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_team_demandante",
                to="management.firefighter",
                verbose_name="Demandante",
            ),
        ),
        migrations.AlterField(
            model_name="serviceteam",
            name="name_m",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_team_m",
                to="management.firefighter",
                verbose_name="M",
            ),
        ),
        migrations.AlterField(
            model_name="serviceteam",
            name="name_s1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_team_s1",
                to="management.firefighter",
                verbose_name="S1",
            ),
        ),
        migrations.AlterField(
            model_name="serviceteam",
            name="name_s2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_team_s2",
                to="management.firefighter",
                verbose_name="S2",
            ),
        ),
    ]
