# Generated by Django 4.2.6 on 2024-07-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_alter_report_anamnesis_alter_report_cinematic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glasgowtype",
            old_name="grater_than_five_year",
            new_name="is_grater_than_five_year",
        ),
        migrations.RemoveField(
            model_name="glasgowtype",
            name="less_than_five_year",
        ),
    ]
