# Generated by Django 4.2.6 on 2024-07-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0012_rename_grater_than_five_year_glasgowtype_is_grater_than_five_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anamnesis",
            options={"verbose_name": "Anamnese", "verbose_name_plural": "Anamneses"},
        ),
        migrations.AlterModelOptions(
            name="cinematic",
            options={
                "verbose_name": "Avaliação Cinemática",
                "verbose_name_plural": "Avaliações Cinemáticas",
            },
        ),
        migrations.AlterModelOptions(
            name="disposablematerials",
            options={
                "verbose_name": "Materiais Descartáveis",
                "verbose_name_plural": "Materiais Descartáveis",
            },
        ),
        migrations.AlterModelOptions(
            name="drivingstyle",
            options={
                "verbose_name": "Forma de Transporte",
                "verbose_name_plural": "Formas de Transportes",
            },
        ),
        migrations.AlterModelOptions(
            name="gestacionalanamnesis",
            options={
                "verbose_name": "Anamnese Gestacional",
                "verbose_name_plural": "Anamneses Gestacionais",
            },
        ),
        migrations.AlterModelOptions(
            name="hospitalmaterials",
            options={
                "verbose_name": "Material Hospitalar",
                "verbose_name_plural": "Material Hospitalar",
            },
        ),
        migrations.AlterModelOptions(
            name="proceeding",
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceteam",
            options={
                "verbose_name": "Equipe de atendimento",
                "verbose_name_plural": "Equipe de atendimento",
            },
        ),
        migrations.AlterModelOptions(
            name="signsandsymptoms",
            options={"verbose_name": "Sintoma", "verbose_name_plural": "Sintomas"},
        ),
        migrations.AlterModelOptions(
            name="subproceeding",
            options={
                "verbose_name": "Sub-Procedimento",
                "verbose_name_plural": "Sub-Procedimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="subsignsandsymptoms",
            options={
                "verbose_name": "Sub-Sintoma",
                "verbose_name_plural": "Sub-Sintomas",
            },
        ),
        migrations.AlterModelOptions(
            name="subsubproceeding",
            options={
                "verbose_name": "Sub-Sub-Procedimento",
                "verbose_name_plural": "Sub-Sub-Procedimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="subsubsignsandsymptoms",
            options={
                "verbose_name": "Sub-Sub-Sintoma",
                "verbose_name_plural": "Sub-Sub-Sintomas",
            },
        ),
        migrations.AlterModelOptions(
            name="subsuspectproblems",
            options={
                "verbose_name": "Sub-Problema Suspeito",
                "verbose_name_plural": "Sub-Problemas Suspeitos",
            },
        ),
        migrations.AlterModelOptions(
            name="suspectproblems",
            options={
                "verbose_name": "Problema Suspeito",
                "verbose_name_plural": "Problemas Suspeitos",
            },
        ),
        migrations.AlterModelOptions(
            name="transportdecision",
            options={
                "verbose_name": "Decisão de Transporte",
                "verbose_name_plural": "Decisões de Transporte",
            },
        ),
        migrations.AlterModelOptions(
            name="transportinformations",
            options={
                "verbose_name": "Informações de transporte",
                "verbose_name_plural": "Informações de transporte",
            },
        ),
        migrations.AlterModelOptions(
            name="typeofoccurrence",
            options={
                "verbose_name": "Tipo de Ocorrência",
                "verbose_name_plural": "Tipos de Ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="victimwas",
            options={"verbose_name": "Vítima", "verbose_name_plural": "Vítimas"},
        ),
        migrations.AlterModelOptions(
            name="vitalsigns",
            options={
                "verbose_name": "Sinal Vital",
                "verbose_name_plural": "Sinais Vitais",
            },
        ),
    ]
