# Generated by Django 4.2.6 on 2024-07-31 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_disposablematerialsstock_hospitalmaterialsstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="disposablematerialsstock",
            name="disposable_materials_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposable_materials",
                to="reports.disposablematerialsstock",
                verbose_name="Estoque de materiais descartáveis",
            ),
        ),
        migrations.AddField(
            model_name="hospitalmaterials",
            name="hospital_materials_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_materials",
                to="reports.hospitalmaterialsstock",
                verbose_name="Estoque de materiais hospitalares",
            ),
        ),
    ]
